services:
  - name: meetx-service
    type: web
    env: java
    plan: starter
    buildCommand: |
      mvn clean install
      ls -l target/
    startCommand: "java -jar target/meet-x-0.0.1-SNAPSHOT.jar"
    branches:
      - master
