name: Java CI with Maven

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4 # Ensure this is the correct version

      - name: Set up JDK 17
        uses: actions/setup-java@v2 # Confirm v2 is correct for stable JDK setup
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean package --file pom.xml

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          curl -fsSL https://render.com/install.sh | sh
          render deploy --service meetX --branch main
