name: Java CI with Maven

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4 # Ensure this is correct version

      - name: Set up JDK 17
        uses: actions/setup-java@v2 # Confirm v2 is correct for stable JDK setup
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean package --file pom.xml # Consider changing based on your needs

      - name: Update dependency graph (Optional)
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Print non-sensitive environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}"
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}"

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Optionally print secrets for debugging (just don't print passwords or sensitive data)
          echo "Deploying to Render..."
          curl -fsSL https://render.com/install.sh | sh
          render deploy --service meetX --branch main
